CREATE TABLE IF NOT EXISTS jeepney_locations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    jeepney_id INT NOT NULL,
    route VARCHAR(100),
    lat DOUBLE NOT NULL,
    lng DOUBLE NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 